### ISSUE TITLE
Improve Legibility on About Page

### ISSUE THREAD

**Issue by jpdevries** [bpcoxjr/times-search#6]
consider making the bg slightly less transparent even if just for the `.about-container`

```css
.about-container {
    background: rgba(255, 255, 255, 0.90);
}
```

![](http://j4p.us/1D0D2M3E1t0z/Screen%20Shot%202016-05-05%20at%207.19.43%20PM.png)
